# Generated by Django 3.1.4 on 2020-12-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_profile_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
